apiVersion: v1
kind: ConfigMap
metadata:
  name: mlo-embed-config
  namespace: default
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  MODEL_NAME: "all-MiniLM-L6-v2"
  MODEL_CACHE: "/app/models"
  API_PORT: "8000"
  MLFLOW_TRACKING_URI: "http://mlflow.default.svc.cluster.local:5000"